package com.donacion.mobile.domain

enum class Rol { DONANTE, RECEPTOR, ADMIN, ADMINISTRADOR }
enum class EstadoPublicacion { PENDIENTE, DISPONIBLE, RESERVADA, ENTREGADA, VENCIDA, CANCELADA, BLOQUEADA, RECHAZADA }
enum class EstadoSolicitud { PENDIENTE, ACEPTADA, RECHAZADA, CANCELADA, ENTREGADA }
enum class UnidadMedida { UNIDAD, KILOGRAMO, LITRO, CAJA, PAQUETE, BANDEJA, PORCION }
