package com.donacion.app.publicacion.domain;

public enum EstadoPublicacion {
	PENDIENTE, PUBLICADA, DISPONIBLE, RESERVADA, RESERVADO, ENTREGADA, ENTREGADO, RECHAZADA, BLOQUEADA, VENCIDA, VENCIDO, CANCELADA, CANCELADO
}
