package com.donacion.app.historial.domain;

public enum TipoOperacion {
    USUARIO_REGISTRADO,
    PUBLICACION_CREADA,
    PUBLICACION_ACTUALIZADA,
    PUBLICACION_DISPONIBLE,
    PUBLICACION_BLOQUEADA,
    SOLICITUD_CREADA,
    SOLICITUD_ACEPTADA,
    SOLICITUD_RECHAZADA,
    SOLICITUD_CANCELADA,
    ENTREGA_CONFIRMADA
}
